#!/bin/bash

#PBS -P RDS-FEI-MIMIC_dataset-RW
#PBS -M tngo9001@uni.sydney.edu.au
#PBS -m abe
#PBS -N project_demo
#PBS -q defaultQ
#PBS -l select=1:ncpus=1:mem=14GB
#PBS -l walltime=2:00:00

module load python/3.9.15

module load java
module load weka

pip install --user javabridge
pip install --user python-weka-wrapper3
pip install pandas scikit-learn imbalanced-learn
pip install pyfaidx --upgrade

cd $PBS_O_WORKDIR
python testing.py > result.out